// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrj4s60NUoD1T5wA-kiPWuvnjbXD0_2js',
    appId: '1:44056119704:web:7bb35e0cf1242260a783ed',
    messagingSenderId: '44056119704',
    projectId: 'fir-card-f1873',
    authDomain: 'fir-card-f1873.firebaseapp.com',
    storageBucket: 'fir-card-f1873.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzoTlScqIC05dNFf155yS_JhCNMSqd7zA',
    appId: '1:44056119704:android:3abfbfb4192a9393a783ed',
    messagingSenderId: '44056119704',
    projectId: 'fir-card-f1873',
    storageBucket: 'fir-card-f1873.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEbekHZhM5hpOZb3i6f6_A1b0bUmEdh-w',
    appId: '1:44056119704:ios:14fd672830444469a783ed',
    messagingSenderId: '44056119704',
    projectId: 'fir-card-f1873',
    storageBucket: 'fir-card-f1873.firebasestorage.app',
    iosBundleId: 'com.scard.scardGame',
  );
}
